version: "3.9"
services:
  pf_database:
    image: postgres:14
    volumes:
      - pf_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  pf_redis:
    image: 'redis:latest'
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - pf_redis:/data
  pixabay_feed:
    build: .
    command: ./bin/start
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - APP_ENV=${APP_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
    depends_on:
      - pf_database
      - pf_redis

volumes:
  pf_postgres: {}
  pf_redis: {}
